# Generated by Django 3.0.8 on 2023-09-27 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
